title: Data visualisation style guide
description: Standards, guidance and template for data visualisations
theme: just-the-docs

url: https://renrmt.github.io/style_guide

aux_links:
  Template Repository: https://github.com/RenRMT/style_guide
